---
title: "Plotting Results"
author: "Joe Brown"
date: "2024-10-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Goal

Plot results in ternary plot that shows the error associated with different numerical combinations of criteria weights. 


# Plots 

Testing out ternary plot code:
```{r}
# Create the ternary plot with error as color
ggtern(data = subset(plotting_list$`SSP1-1.9`, term_length == "short"), aes(x = temp_wt, y = CO2_wt, z = ocean_uptake_wt, color = median_error)) +
  geom_point(size = 1, shape = 15) +
  scale_color_gradient(low = "blue", high = "red") +
  theme_light() +
  theme_showarrows() +
  theme_arrowlarge() +
  theme_hidetitles() +
  xlab("Temperature Weight") +
  ylab("CO2 Weight") +
  zlab("Ocean C Uptake Weight") +
  labs(
    title = "Error of central value",
    color = "Percent Error"
  )

ggsave("example_figure.png", 
       device = "png", 
       height = 4.5, 
       width = 7.29, 
       units = "in")

```
```{r}
term_lengths_list <- list("short", "mid", "long")
error <- list("median_error", "lower_error", "upper_error")

lapply(names(plotting_list), function(scenario_names) {
  print(paste("processing scenario:", scenario_names))

  data = plotting_list[[scenario_names]]
    
  lapply(term_lengths_list, function(term_length) {
    print(paste("processing term length:", term_length))
    
    lapply(error, function(error_term) {
      print(paste("processing error term:", error_term))
    
      plot_ternary(data, term_length = term_length, error = data[[error_term]], 
               filepath = paste0("figures/", scenario_names, "_", term_length, "_", error_term, ".png"))
      
    })
  })
})
```

